FROM debian

WORKDIR /src

RUN apt-get update
RUN apt-get install -y tar git curl nano wget dialog net-tools build-essential smartmontools
RUN apt-get install -y python python-dev python-distribute python-pip

EXPOSE 8081
